spring:
  #mvc:
  #  static-path-pattern=: /res/**

  resources:
    static-locations: [classpath:/abc/]

  contentnegotiation:
    favor-parameter: true

  mvc:
    hiddenmethod:
      filter:
        enable: true
server:
  servlet:
    context-path: /world
